### ISSUE TITLE
The following packages have unmet dependencies:  mongodb-org-server : Depends: libssl1.0.0 (>= 1.0.2~beta3) but it is not installable

### ISSUE THREAD

**Issue by BxtGeek** [lawrencesystems/youtubedemos#1]
root@unifi:~# sudo apt-get update && sudo apt-get install unifi -y
Ign:1 https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.4 InRelease
Hit:2 http://archive.ubuntu.com/ubuntu jammy InRelease                      
Hit:3 https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.4 Release    
Hit:5 http://archive.ubuntu.com/ubuntu jammy-updates InRelease      
Hit:7 http://archive.ubuntu.com/ubuntu jammy-security InRelease
Hit:6 https://dl.ubnt.com/unifi/debian stable InRelease
Reading package lists... Done
W: https://repo.mongodb.org/apt/ubuntu/dists/xenial/mongodb-org/3.4/Release.gpg: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 mongodb-org-server : Depends: libssl1.0.0 (>= 1.0.2~beta3) but it is not installable
E: Unable to correct problems, you have held broken packages.
root@unifi:~#

**Comment by lawrencesystems** [comment]
As I said in the video Ubuntu 22.04 is not well supported with MongoDB which is why I said to use 20.04.

**Comment by BxtGeek** [comment]
Thanks for confirming will try this with ubuntu 20.04
